# Generated by Django 4.2.6 on 2023-11-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_type',
        ),
        migrations.DeleteModel(
            name='FeedbackType',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.JSONField(default=list),
        ),
    ]
