# Generated by Django 4.2.6 on 2023-11-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
