# Generated by Django 4.2.6 on 2023-11-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menu_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menu',
            name='launch_status',
            field=models.BooleanField(default=False),
        ),
    ]
